[package]
name = "codewars"
version = "0.1.0"
authors = ["Łukasz Staniszewski <kontakt@lukaszstaniszewski.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "codewars"
path = "src/lib.rs"

[dependencies]
